#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: github-external-service
#spec:
#  hosts:
#  - api.github.com
#  ports:
#  - number: 443
#    name: https
#    protocol: HTTPS
#  - number: 80
#    name: http
#    protocol: HTTP
#  resolution: DNS
#  location: MESH_EXTERNAL
